version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_name: "HoneybeeSchema"
          update_type: "all"
    commit_message:
      prefix: "fix"
      include_scope: true
