name: Pull_Request_Tests

on: 
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2

      - name: Build
        working-directory: src/Honeybee.UI
        run: |
          dotnet build Honeybee.UI.csproj --configuration Release 
          