name: CD

on:
  push:
    branches: [master]

jobs:
  build:
    name: "Build and release"
    runs-on: windows-latest

    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v4

      - name: Compile
        working-directory: src/Honeybee.UI
        run: |
          dotnet build Honeybee.UI.csproj --configuration Release /nowarn:CS0472,CS0108 --force --no-incremental
          ls bin -R

      - name: Zip Build Artifact
        run: |
          Compress-Archive -U -Path src\Honeybee.UI\bin\Release\* -DestinationPath HoneybeeUI

      - uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Deploy
        if: steps.semantic.outputs.new_release_published == 'true'
        working-directory: src/Honeybee.UI
        run: |
          echo "Removing existing builds"
          dotnet clean Honeybee.UI.csproj -c Release
          rm -r -fo bin

          echo "Rebuilding Honeybee.UI with the new version......"
          dotnet build Honeybee.UI.csproj -p:Version=${{ steps.semantic.outputs.new_release_version }} --configuration Release --force
          echo "Deploying Honeybee.UI......"
          dotnet nuget push bin\Release\Honeybee.UI.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
